
server:
  port: 8081
security:
  basic:
    enabled: true
  user:
    name: gaobin
    password: gaobin123
  eureka:
    instance:
      hostname: localhost
      prefer-ip-address: true
    client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://gaobin:gaobin123@localhost:${server.port}/eureka/
